### PR TITLE
Create a dummy progress bar class.

### PR DESCRIPTION
**Pull request by dkfellows**
This will allow us to keep code elsewhere much simpler by moving the decision of whether the progress bar actually prints anything into a single place in that code.

### CODE REVIEW

**Comment by dkfellows** [comment]
**NB:** Higher level decision of whether code _should_ use a dummy progress bar or a real one is out of scope of this PR; the utilities classes don't have the information to take it.

**Comment by alan-stokes** [comment]
dont renemebr why this exists.

**Comment by rowleya** [comment]
I can see the theory - you can have various functions take a progress bar for example, and then you can choose whether to actually display progress by choosing which bar to pass.  Avoids a number of None checks.  The obvious places that this might work well with are SpiNNMan methods, where knowing the sub-progress of a command could be useful in some contexts.

**Comment by alan-stokes** [comment]
ok, well ill emrge then, it looks fine, jsut cant personally see where itll be used. but if ya can, then so be it

**Pull request merged**
