### PR TITLE
Create python-package.yml file

### PR DESCRIPTION
**Pull request by andrewgait**
Try using GitHub Actions...

### CODE REVIEW

**Review by Christian-B — COMMENTED** [review]
Looks good for a start.

I would suggest merging ASAP and travis is no longer an options for us.

**Review by rowleya — APPROVED** [review]
I think that this does everything except sphinx.  If we are happy without that, this is fine.

**Review by alan-stokes — APPROVED** [review]

**Comment by andrewgait** [comment]
> I think that this does everything except sphinx. If we are happy without that, this is fine.

I can try adding sphinx as well - I left it out of the first tries for the sake of simplicity only.

**Comment by andrewgait** [comment]
Do you want me to edit this (or start a new PR) to match better what's been done on SpiNNMachine and SpiNNMan?

**Comment by dkfellows** [comment]
I found an idea for skipping tests in some circumstances at https://github.com/microsoft/topologic/pull/38 which I'll rework into a better way to skip the ping testing.

**Review by dkfellows — APPROVED** [review]

**Pull request merged**
