### PR TITLE
Type annotations experiment

### PR DESCRIPTION
**Pull request by dkfellows**
This is an _experiment_ in adding type annotations and checking. (It's ahead of the `end-27` branch.)

Alas, Sphinx's treatment of type annotations leaves something to be desired, at least up to 3.9. (There are numerous issues on the matter.)

### CODE REVIEW

**Comment by dkfellows** [comment]
The place where I've _really_ done type annotations (so far) is just `abstract_dict.py`. The other files have just had enough put in to make them pass the `mypy` typecheck I've added.

**Comment by dkfellows** [comment]
Example of type description rendered by Sphinx and why it's currently something of a problem:

> **iter_all_values**(_key: Optional[Union[str, Iterable[str]]], update_save: bool = False_) → Iterator[Union[int, float, Iterable[int], Iterable[float]]]

I actually wrote `def iter_all_values(self, key:KeyType, update_save:bool=False) -> Iterator[ValueType]:` to get that; `KeyType` and `ValueType` are aliases, and far more informative than their concrete types.

**Comment by dkfellows** [comment]
FWIW, I don't exactly recommend type annotations, at least not for everything. They can help with new work, but they're a bit of a pain in some cases.

**Comment by Christian-B** [comment]
Is there anything useful in this branch that can not be found in https://github.com/SpiNNakerManchester/SpiNNUtils/pull/233

**Comment by Christian-B** [comment]
Done in another branch

**Pull request closed without merging**
