### PR TITLE
UGLY hack to provide hash

### PR DESCRIPTION
**Pull request by Christian-B**

### CODE REVIEW

**Comment by rowleya** [comment]
This would *have* to override __eq__ to be correct, as stated in the comment, otherwise the required property is broken.  If you know that the elements won't change, put the set in a frozenset before adding to the thing that requires it to be hashable.

**Comment by rowleya** [comment]
To add, if the elements are to change, it shouldn't be added to a set, as you won't really know that it is in there anyway!

**Comment by Christian-B** [comment]
The Goal was to have a SET that could be added  to yet retain the same hash.

===

The question is however if that is a desiarable goal. Which is why this pull request is labeled "Won't fix"

@alan-stokes if you no longer need this UGLY hack close the PR and delete the branch!

**Comment by rowleya** [comment]
The main point is that if there is a use case for this, I would like to hear it, otherwise, yes, please close the PR and delete!

**Pull request closed without merging**
