### PR TITLE
Nuke deplicate code

### PR DESCRIPTION
**Pull request by Christian-B**
Same code was in FEC from where it was being called

### CODE REVIEW

**Comment by alan-stokes** [comment]
pay more attention christian. those two functions are not line by line equiv. please verify which one is really right.

**Comment by Christian-B** [comment]
As Alan thinks (don't ask me why) that these uncalled functions need to stay closing this as not wasting tnme merging an unwanted pr

**Comment by rowleya** [comment]
I don't think this should be left - I think Alan was worried that the code was not the same.  If it also isn't ever called, I think we can nuke them in any case (as the called versions seem to work).

**Comment by rowleya** [comment]
A quick test shows that this is indeed not used, so I will re-open...

**Pull request merged**
